/**
 * One-word place names shared by too many DIFFERENT places to identify any of
 * them — "Edelweiss" names 57 places in this dataset, "Alpina" 69.
 *
 * ⚠️ GENERATED by scripts/generate-shared-names.ts. Do not edit by hand; the
 * hand-written version this replaced had 28 entries and missed 196 the data
 * knew about. Re-run after regenerating hut data.
 *
 * Used by the photo searches, which match a hut to a picture BY NAME. A name on
 * this list cannot carry a match alone: Commons declines to search at all
 * (it has no position to corroborate with), and Flickr demands a geotag beside
 * the hut. Without that, a guesthouse in the Valais was shown a Pension
 * Edelweiss in the Harz.
 *
 * 224 names, shared by 2591 of 23,194 named places.
 */
export const SHARED_PLACE_NAMES: ReadonlySet<string> = new Set([
  'wilderness', 'alpine', 'alpina', 'lovska', 'edelweiss', 'alpenrose',
  'agriturismo', 'panorama', 'belvedere', 'bellevue', 'alpenblick', 'alpenhof',
  'alpes', 'grand', 'montana', 'berghof', 'blanc', 'edelwei',
  'gastehaus', 'malga', 'miramonti', 'residence', 'sonne', 'villa',
  'cristallo', 'monte', 'naturfreundehaus', 'alpino', 'central', 'krone',
  'astoria', 'hubertus', 'kristall', 'bellavista', 'chamois', 'regina',
  'bergkristall', 'cabana', 'casera', 'enzian', 'etape', 'hirschen',
  'maria', 'sonnenhof', 'baren', 'berggasthof', 'jagerhof', 'adler',
  'berger', 'bergland', 'bucaneve', 'diana', 'dolomiti', 'hapimag',
  'olympia', 'posta', 'aurora', 'bergheim', 'europa', 'genzianella',
  'lodge', 'petit', 'pineta', 'sport', 'tirolerhof', 'alpin',
  'communal', 'della', 'genziana', 'kreuz', 'melezes', 'rosengarten',
  'schweizerhof', 'steinbock', 'tyrol', 'waldheim', 'airelles', 'almhof',
  'bergblick', 'berghutte', 'centrale', 'elisabeth', 'glacier', 'gletscherblick',
  'landhaus', 'larchenhof', 'miravalle', 'napoleon', 'paradiso', 'savoia',
  'sonnhof', 'albergue', 'alpengasthof', 'alpenruh', 'alpini', 'breakfast',
  'campo', 'ciasa', 'cresta', 'enzianhutte', 'hubertushof', 'milano',
  'royal', 'scoiattolo', 'stern', 'waldesruh', 'antiaereo', 'anton',
  'arnika', 'belmont', 'bergwelt', 'birkenhof', 'blanche', 'bristol',
  'cervo', 'christiania', 'forestiere', 'jagdhof', 'montanara', 'neuwirt',
  'nevada', 'pescadores', 'piccolo', 'schonblick', 'serena', 'silvretta',
  'soleil', 'sporting', 'tirol', 'wiesenhof', 'wieser', 'winterraum',
  'alpenland', 'appartements', 'bianca', 'bianco', 'cimes', 'concordia',
  'corona', 'derby', 'engel', 'erika', 'fanes', 'fontana',
  'france', 'gitem', 'huber', 'jagerheim', 'marmotte', 'poste',
  'rododendro', 'romantica', 'sciora', 'sejour', 'soldanelle', 'sommafiume',
  'sportalm', 'suisse', 'traube', 'valle', 'vanoise', 'victoria',
  'walliserhof', 'alaska', 'albert', 'alpen', 'antonio', 'aparthotel',
  'arnica', 'bergerie', 'bergfrieden', 'biancaneve', 'bosco', 'bruno',
  'bruyeres', 'capitelle', 'caribou', 'carlines', 'christina', 'clarines',
  'crystal', 'ecureuil', 'ermitage', 'ferme', 'fonts', 'forestale',
  'fuchsegg', 'gardenia', 'gotthard', 'grange', 'hostal', 'italia',
  'jahreszeiten', 'kirchenwirt', 'lowen', 'marco', 'martin', 'mitterberghutten',
  'montanina', 'moosalm', 'negritella', 'piana', 'pierre', 'ponte',
  'sailer', 'savoy', 'sciatori', 'skihutte', 'sonnalm', 'sonneck',
  'sonnenalm', 'sonnenberg', 'sporthotel', 'steiner', 'stella', 'sternen',
  'tannenhof', 'tremplin', 'venezia', 'viktoria', 'vittoria', 'waldhaus',
  'weber', 'wellness',
]);
