/**
 * One-word place names shared by too many DIFFERENT places to identify any of
 * them — "Edelweiss" names 75 places in this dataset, "Alpina" 69.
 *
 * ⚠️ GENERATED by scripts/generate-shared-names.ts. Do not edit by hand; the
 * hand-written version this replaced had 28 entries and missed 194 the data
 * knew about. Re-run after regenerating hut data.
 *
 * Used by the Commons photo search, which matches a hut to a picture BY NAME.
 * A name on this list cannot carry a match alone and the search declines
 * rather than guessing, because a Commons file carries no position to
 * corroborate with. Without that, a guesthouse in the Valais was shown a
 * Pension Edelweiss in the Harz and a Haus Edelweiss on the Baltic coast.
 *
 * 222 names, shared by 2575 of 23,194 named places.
 */
export const SHARED_PLACE_NAMES: ReadonlySet<string> = new Set([
  'wilderness', 'alpine', 'edelweiss', 'alpina', 'lovska', 'alpenrose',
  'agriturismo', 'panorama', 'belvedere', 'bellevue', 'alpenblick', 'alpenhof',
  'alpes', 'grand', 'montana', 'blanc', 'berghof', 'malga',
  'miramonti', 'residence', 'sonne', 'villa', 'cristallo', 'gastehaus',
  'monte', 'naturfreundehaus', 'alpino', 'central', 'krone', 'astoria',
  'hubertus', 'kristall', 'bellavista', 'chamois', 'regina', 'bergkristall',
  'cabana', 'casera', 'enzian', 'etape', 'hirschen', 'maria',
  'sonnenhof', 'baren', 'berggasthof', 'jagerhof', 'adler', 'berger',
  'bergland', 'bucaneve', 'diana', 'dolomiti', 'hapimag', 'olympia',
  'posta', 'aurora', 'bergheim', 'europa', 'genzianella', 'lodge',
  'petit', 'pineta', 'sport', 'tirolerhof', 'alpin', 'communal',
  'della', 'genziana', 'melezes', 'rosengarten', 'schweizerhof', 'steinbock',
  'tyrol', 'waldheim', 'airelles', 'almhof', 'bergblick', 'centrale',
  'elisabeth', 'glacier', 'gletscherblick', 'kreuz', 'landhaus', 'larchenhof',
  'miravalle', 'napoleon', 'paradiso', 'savoia', 'sonnhof', 'albergue',
  'alpenruh', 'alpini', 'breakfast', 'campo', 'ciasa', 'cresta',
  'enzianhutte', 'hubertushof', 'milano', 'royal', 'scoiattolo', 'stern',
  'waldesruh', 'alpengasthof', 'antiaereo', 'anton', 'arnika', 'belmont',
  'bergwelt', 'birkenhof', 'blanche', 'bristol', 'cervo', 'christiania',
  'forestiere', 'jagdhof', 'montanara', 'neuwirt', 'nevada', 'pescadores',
  'piccolo', 'schonblick', 'serena', 'silvretta', 'soleil', 'sporting',
  'tirol', 'wiesenhof', 'wieser', 'winterraum', 'alpenland', 'appartements',
  'berghutte', 'bianca', 'bianco', 'cimes', 'concordia', 'corona',
  'derby', 'engel', 'erika', 'fanes', 'fontana', 'france',
  'gitem', 'huber', 'jagerheim', 'marmotte', 'poste', 'rododendro',
  'romantica', 'sciora', 'sejour', 'soldanelle', 'sommafiume', 'sportalm',
  'suisse', 'traube', 'valle', 'vanoise', 'victoria', 'walliserhof',
  'alaska', 'albert', 'alpen', 'antonio', 'aparthotel', 'arnica',
  'bergerie', 'bergfrieden', 'biancaneve', 'bosco', 'bruno', 'bruyeres',
  'capitelle', 'caribou', 'carlines', 'christina', 'clarines', 'crystal',
  'ecureuil', 'ermitage', 'ferme', 'fonts', 'forestale', 'fuchsegg',
  'gardenia', 'gotthard', 'grange', 'hostal', 'italia', 'jahreszeiten',
  'kirchenwirt', 'lowen', 'marco', 'martin', 'mitterberghutten', 'montanina',
  'moosalm', 'negritella', 'piana', 'pierre', 'ponte', 'sailer',
  'savoy', 'sciatori', 'sonnalm', 'sonneck', 'sonnenalm', 'sonnenberg',
  'sporthotel', 'steiner', 'stella', 'sternen', 'tannenhof', 'tremplin',
  'venezia', 'viktoria', 'vittoria', 'waldhaus', 'weber', 'wellness',
]);
