/**
 * Write `src/constants/sharedNames.ts`: the one-word place names that too many
 * DIFFERENT places share to identify any of them.
 *
 * WHY: the photo searches match a hut to a picture by name. That works for
 * "Karwendelhaus" and fails badly for "Pension Edelweiss" — 57 different places
 * carry that name, so Commons happily returned a Pension Edelweiss in the Harz
 * and a Haus Edelweiss on the Baltic coast for a guesthouse in the Valais.
 *
 * Generated rather than hand-written because a hand-written list was wrong:
 * it had 28 entries and missed 196 more that the data itself knows about.
 *
 * ⚠️ DEDUPE BY OSM ID. Region files overlap by HALO_KM, so the same hut appears
 * in several of them; counting naively inflated every name several-fold and put
 * genuinely unique names like "larribet" on the list.
 *
 * Run: npm run generate-shared-names   (after regenerating hut data)
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { distinctiveTokens, normalizePlaceName } from '../src/utils/dedupePlaces';
import type { Hut } from '../src/types/hut';

/** How many distinct places must share a name before it identifies none of
 *  them. At 5 this covers 2,591 of 23,194 named places; lowering it to 4 starts
 *  catching real hut names like Schwarzenberghütte, of which there genuinely
 *  are four. */
const MIN_SHARED = 5;

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'assets', 'data', 'regions');
const OUT = join(ROOT, 'src', 'constants', 'sharedNames.ts');

const byId = new Map<string, Hut>();
for (const f of readdirSync(DIR).filter((x) => x.endsWith('.json') && x !== '_meta.json')) {
  const d = JSON.parse(readFileSync(join(DIR, f), 'utf8')) as Record<string, Hut[]>;
  for (const bucket of ['core', 'accommodations']) {
    for (const h of d[bucket] ?? []) if (h.name) byId.set(h.id, h);
  }
}

const count = new Map<string, number>();
for (const h of byId.values()) {
  const t = distinctiveTokens(normalizePlaceName(h.name));
  // Only ONE-WORD names can be ambiguous on their own; "Cabane de Prafleuri"
  // carries enough to identify itself.
  if (t.length !== 1) continue;
  count.set(t[0], (count.get(t[0]) ?? 0) + 1);
}

const shared = [...count.entries()]
  .filter(([, n]) => n >= MIN_SHARED)
  .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));

const lines: string[] = [];
for (let i = 0; i < shared.length; i += 6) {
  lines.push('  ' + shared.slice(i, i + 6).map(([w]) => `'${w}',`).join(' '));
}

writeFileSync(
  OUT,
  `/**
 * One-word place names shared by too many DIFFERENT places to identify any of
 * them — "Edelweiss" names ${count.get('edelweiss') ?? 0} places in this dataset, "Alpina" ${count.get('alpina') ?? 0}.
 *
 * ⚠️ GENERATED by scripts/generate-shared-names.ts. Do not edit by hand; the
 * hand-written version this replaced had 28 entries and missed ${shared.length - 28} the data
 * knew about. Re-run after regenerating hut data.
 *
 * Used by the photo searches, which match a hut to a picture BY NAME. A name on
 * this list cannot carry a match alone: Commons declines to search at all
 * (it has no position to corroborate with), and Flickr demands a geotag beside
 * the hut. Without that, a guesthouse in the Valais was shown a Pension
 * Edelweiss in the Harz.
 *
 * ${shared.length} names, shared by ${shared.reduce((s, [, n]) => s + n, 0)} of ${byId.size.toLocaleString()} named places.
 */
export const SHARED_PLACE_NAMES: ReadonlySet<string> = new Set([
${lines.join('\n')}
]);
`,
  'utf8',
);

console.log(
  `${byId.size.toLocaleString()} distinct named places\n` +
    `${shared.length} names shared by ${MIN_SHARED}+ places, covering ` +
    `${shared.reduce((s, [, n]) => s + n, 0).toLocaleString()} of them\n` +
    `-> ${OUT}`,
);
