// A VALUE import, not a type one — the dev-time orphan check below needs the
// actual region list. `region.ts` imports nothing from here, so no cycle.
import { REGIONS } from '../constants/region';
import type { Hut } from '../types/hut';
import type { Ride } from '../types/ride';

interface RegionData {
  core: Hut[];
  accommodations: Hut[];
  villages: Hut[];
  /** Lifts/trains. Optional because rides are generated on a best-effort basis
   *  — see `bundledRides`. */
  rides?: Ride[];
}

// The pre-fetched offline snapshot, generated by `npm run generate-huts` and
// shipped inside the app, split into ONE FILE PER REGION. Only the region(s) the
// user actually picked get `require`d/parsed at runtime — so a small selection
// parses ~250-530 KB instead of the whole ~5.2 MB in one go (the whole-bundle
// parse was ~80 ms on desktop, noticeably more on device, and happened at
// startup regardless of how few regions were chosen). Metro still bundles every
// file, but Hermes only parses the ones whose thunk is called.
//
// `require` (not `import`): a multi-MB JSON `import` makes tsc infer the entire
// literal as a type (slow/memory-hungry); `require` is `any`-typed so tsc never
// parses it. Static string paths are required by Metro — hence the explicit map
// rather than a dynamic path. Keep this list in sync with `REGIONS` (and re-run
// the generator, which writes these files) if regions are added/removed.
const REGION_THUNKS: Record<string, () => RegionData> = {
  'bernese-oberland': () => require('../../assets/data/regions/bernese-oberland.json'),
  'valais-west': () => require('../../assets/data/regions/valais-west.json'),
  'valais-east': () => require('../../assets/data/regions/valais-east.json'),
  ticino: () => require('../../assets/data/regions/ticino.json'),
  'central-switzerland': () => require('../../assets/data/regions/central-switzerland.json'),
  'graubunden-north': () => require('../../assets/data/regions/graubunden-north.json'),
  'graubunden-engadin': () => require('../../assets/data/regions/graubunden-engadin.json'),
  dolomites: () => require('../../assets/data/regions/dolomites.json'),
  'dolomiti-bellunesi': () =>
    require('../../assets/data/regions/dolomiti-bellunesi.json'),
  'aosta-valley': () => require('../../assets/data/regions/aosta-valley.json'),
  'ortler-stelvio': () => require('../../assets/data/regions/ortler-stelvio.json'),
  trentino: () => require('../../assets/data/regions/trentino.json'),
  'lombardy-alps': () => require('../../assets/data/regions/lombardy-alps.json'),
  'julian-carnic-alps': () => require('../../assets/data/regions/julian-carnic-alps.json'),
  'piedmont-alps': () => require('../../assets/data/regions/piedmont-alps.json'),
  // --- France ---
  'mont-blanc-chablais': () => require('../../assets/data/regions/mont-blanc-chablais.json'),
  vanoise: () => require('../../assets/data/regions/vanoise.json'),
  ecrins: () => require('../../assets/data/regions/ecrins.json'),
  'queyras-brianconnais': () => require('../../assets/data/regions/queyras-brianconnais.json'),
  mercantour: () => require('../../assets/data/regions/mercantour.json'),
  corsica: () => require('../../assets/data/regions/corsica.json'),
  'vercors-chartreuse': () => require('../../assets/data/regions/vercors-chartreuse.json'),
  'pyrenees-bearn': () => require('../../assets/data/regions/pyrenees-bearn.json'),
  'pyrenees-centrales': () => require('../../assets/data/regions/pyrenees-centrales.json'),
  'pyrenees-ariege': () => require('../../assets/data/regions/pyrenees-ariege.json'),
  // --- Austria ---
  'vorarlberg-lechtal': () => require('../../assets/data/regions/vorarlberg-lechtal.json'),
  'tirol-otztal-zillertal': () => require('../../assets/data/regions/tirol-otztal-zillertal.json'),
  'hohe-tauern': () => require('../../assets/data/regions/hohe-tauern.json'),
  'salzburg-dachstein': () => require('../../assets/data/regions/salzburg-dachstein.json'),
  carinthia: () => require('../../assets/data/regions/carinthia.json'),
  'lower-austria-alps': () => require('../../assets/data/regions/lower-austria-alps.json'),
  // --- Germany ---
  'allgau-werdenfels': () => require('../../assets/data/regions/allgau-werdenfels.json'),
  'bavarian-alps-east': () => require('../../assets/data/regions/bavarian-alps-east.json'),
  'black-forest': () => require('../../assets/data/regions/black-forest.json'),
  // --- Spain ---
  'picos-de-europa': () => require('../../assets/data/regions/picos-de-europa.json'),
  'cantabrian-west': () => require('../../assets/data/regions/cantabrian-west.json'),
  'pirineos-aragon': () => require('../../assets/data/regions/pirineos-aragon.json'),
  'pirineos-catalunya': () => require('../../assets/data/regions/pirineos-catalunya.json'),
  // --- Portugal ---
  'peneda-geres': () => require('../../assets/data/regions/peneda-geres.json'),
  // --- Slovenia ---
  'julian-alps-slovenia': () => require('../../assets/data/regions/julian-alps-slovenia.json'),
  'kamnik-karavanke': () => require('../../assets/data/regions/kamnik-karavanke.json'),
  pohorje: () => require('../../assets/data/regions/pohorje.json'),
  'sneznik-karst': () => require('../../assets/data/regions/sneznik-karst.json'),
  // --- Nordics ---
  'kungsleden-north': () => require('../../assets/data/regions/kungsleden-north.json'),
  jotunheimen: () => require('../../assets/data/regions/jotunheimen.json'),
};

// ⚠️ THIS LIST IS HAND-MAINTAINED AND IT SILENTLY ROTS.
//
// Metro needs literal `require` paths, so adding a region means editing here as
// well as in `REGIONS` — and forgetting is invisible: the generator happily
// fetches the region, writes its file and stamps it complete, `_meta.json`
// reports a healthy hut count, and the region still resolves to NOTHING at
// runtime. Kungsleden, Jotunheimen and Šnežnik all sat generated-but-unreachable
// this way, which read as "Kungsleden's stage ids are wrong" when the ids were
// perfect. So fail loudly in development instead.
// `typeof` guard, not a bare `__DEV__`: this module is also imported by the
// build-time scripts under plain Node, where that global doesn't exist and a
// bare reference throws.
if (typeof __DEV__ === 'undefined' || __DEV__) {
  const orphans = REGIONS.filter((r) => !REGION_THUNKS[r.id]).map((r) => r.id);
  if (orphans.length)
    console.error(
      `hutBundle: ${orphans.length} region(s) in REGIONS have no entry in ` +
        `REGION_THUNKS and will load as empty: ${orphans.join(', ')}. ` +
        `Add a require() line for each.`,
    );
}

// Memoise the parsed module per region — `require` already caches, but this
// keeps the access path a plain Map lookup after the first hit.
const cache = new Map<string, RegionData>();
function regionData(regionId: string): RegionData | undefined {
  const cached = cache.get(regionId);
  if (cached) return cached;
  const thunk = REGION_THUNKS[regionId];
  if (!thunk) return undefined;
  const data = thunk() as unknown as RegionData;
  cache.set(regionId, data);
  return data;
}

const META = require('../../assets/data/regions/_meta.json') as {
  generatedAt: number;
  /** regionId -> core+accommodation count. Absent on bundles generated before
   *  this was added, in which case treat every region as populated. */
  counts?: Record<string, number>;
};

/** When the shipped snapshot was generated (ms epoch). */
export const BUNDLE_GENERATED_AT: number = META.generatedAt;

/**
 * How many huts a region ships, without parsing its file.
 *
 * A region can exist in `REGIONS` before its data does — newly added countries
 * ship as empty placeholders until `npm run generate-huts` fills them. The picker
 * uses this to mark those as having no data yet, rather than letting someone
 * choose a region and find an empty map. Reads only the tiny `_meta.json`, so it
 * doesn't defeat the lazy per-region parsing.
 */
export function bundledRegionHutCount(regionId: string): number {
  // No counts (older bundle) ⇒ assume populated, matching prior behaviour.
  if (!META.counts) return 1;
  return META.counts[regionId] ?? 0;
}

export function bundledCoreHuts(regionId: string): Hut[] | undefined {
  return regionData(regionId)?.core;
}
export function bundledAccommodations(regionId: string): Hut[] | undefined {
  return regionData(regionId)?.accommodations;
}
/**
 * Bundled lifts/trains for a region, or `undefined` if this region's rides were
 * never generated.
 *
 * ⚠️ `undefined` and `[]` mean DIFFERENT things and callers must not conflate
 * them: `[]` is "generated, genuinely no rides here"; `undefined` is "not
 * generated", which is the signal to fall back to a live Overpass fetch. Rides
 * are deliberately allowed to lag behind the hut data — they cost an extra DEM
 * lookup per region, so the generator never lets a missing ride list hold the
 * whole dataset back.
 */
export function bundledRides(regionId: string): Ride[] | undefined {
  return regionData(regionId)?.rides;
}

export function bundledVillages(regionId: string): Hut[] | undefined {
  return regionData(regionId)?.villages;
}

// Flat id→hut index across EVERY region's core + accommodations + villages.
// Building it forces every region to parse, so this is ONLY used off the startup
// path (the hut-detail screen, on demand) to resolve a place by id regardless of
// which regions are loaded — e.g. a hut from a saved route in an unselected
// region.
//
// Villages are included because they can now be tapped on the map and added to a
// route as intermediate stops, which means their detail screen has to resolve
// too. Without them, opening a village's details showed nothing unless it
// happened to be in the current trip (the screen's only other fallback).
let byIdIndex: Map<string, Hut> | null = null;
/**
 * Every bundled place, with the region it came from — built once, lazily.
 *
 * ⚠️ This deliberately parses ALL regions, which the per-region lazy loading
 * otherwise avoids. Search must be able to find any place by name regardless of
 * which regions are selected: someone searching "Kandersteg" wants Kandersteg,
 * and being told it doesn't exist because it sits one region over is simply
 * wrong. The cost is paid only when you actually search (and `bundledHutById`
 * already parses everything for the same reason), then cached for the session.
 */
let placeIndex: { hut: Hut; regionId: string }[] | null = null;

function buildPlaceIndex(): { hut: Hut; regionId: string }[] {
  if (placeIndex) return placeIndex;
  const out: { hut: Hut; regionId: string }[] = [];
  const seen = new Set<string>();
  for (const regionId of Object.keys(REGION_THUNKS)) {
    const d = regionData(regionId);
    if (!d) continue;
    // Region bboxes overlap on purpose, so the same place can appear twice.
    for (const group of [d.core, d.accommodations, d.villages]) {
      for (const h of group) {
        if (seen.has(h.id)) continue;
        seen.add(h.id);
        out.push({ hut: h, regionId });
      }
    }
  }
  placeIndex = out;
  return out;
}

/**
 * Fold a name for searching: lowercase, accents stripped, punctuation flattened.
 *
 * ⚠️ ACCENT FOLDING IS NOT COSMETIC. OSM spells the Sella hut "Rifugio Boé"
 * (acute); every guidebook and every user types "Boè" (grave). Without folding,
 * those are different strings and the hut is simply unfindable — it looked like
 * missing data, and a classic route was published with the stage omitted because
 * of it. The same applies to Blüemlisalp/Bluemlisalp, Grünhorn/Grunhorn, and any
 * name someone types without reaching for the accent key.
 */
function foldForSearch(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

/** Name search across EVERY region, not just the selected ones. */
export function searchBundledPlaces(
  query: string,
  limit = 25,
): { hut: Hut; regionId: string }[] {
  const q = foldForSearch(query);
  if (q.length < 2) return [];
  const out: { hut: Hut; regionId: string }[] = [];
  for (const entry of buildPlaceIndex()) {
    if (foldForSearch(entry.hut.name).includes(q)) {
      out.push(entry);
      if (out.length >= limit) break;
    }
  }
  return out;
}

/** Which bundled region a place belongs to (undefined if it isn't bundled). */
export function bundledRegionOf(hutId: string): string | undefined {
  return buildPlaceIndex().find((e) => e.hut.id === hutId)?.regionId;
}

export function bundledHutById(id: string): Hut | undefined {
  if (!byIdIndex) {
    const idx = new Map<string, Hut>();
    for (const regionId of Object.keys(REGION_THUNKS)) {
      const d = regionData(regionId);
      if (!d) continue;
      for (const h of d.villages) idx.set(h.id, h);
      for (const h of d.accommodations) idx.set(h.id, h);
      for (const h of d.core) idx.set(h.id, h); // core wins over the rest
    }
    byIdIndex = idx;
  }
  return byIdIndex.get(id);
}
